/*
 * The versions come from the jars' pom.properties; one that cannot be read is null.
 */
package com.pingidentity.ps.oidf.platform.pf.health;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNull;

import java.io.IOException;
import java.net.URL;
import java.net.URLClassLoader;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Map;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

class BuildInfoTest {

    private static ClassLoader loaderWith(Path root, String path, String content) throws IOException {
        Path file = root.resolve(path);
        Files.createDirectories(file.getParent());
        Files.writeString(file, content);
        return new URLClassLoader(new URL[] {root.toUri().toURL()}, null);
    }

    @Test
    void theVersionsAreReadFromEachJarsPomProperties(@TempDir Path root) throws IOException {
        loaderWith(root, BuildInfo.OWN_POM, "version=0.5.0\n");
        ClassLoader loader = loaderWith(root, BuildInfo.PINGFEDERATE_POM, "#Generated by Maven\ngroupId=pingfederate\nversion=13.1.3.0\n");
        Map<String, Object> info = BuildInfo.read(loader);
        assertEquals("0.5.0", info.get("agentic-identity"));
        assertEquals("13.1.3.0", info.get("pingfederate"));
        assertNull(info.get("commit"), "no build records the commit yet (F-0190)");
        assertEquals(Runtime.version().toString(), info.get("java"));
    }

    @Test
    void aVersionThatCannotBeReadIsNull(@TempDir Path root) throws IOException {
        assertNull(BuildInfo.version(null, BuildInfo.OWN_POM));
        assertNull(BuildInfo.version(new URLClassLoader(new URL[0], null), BuildInfo.OWN_POM));
        assertNull(BuildInfo.version(loaderWith(root, BuildInfo.OWN_POM, "groupId=x\n"), BuildInfo.OWN_POM));
        assertNull(BuildInfo.version(loaderWith(root, BuildInfo.PINGFEDERATE_POM, "version=  \n"), BuildInfo.PINGFEDERATE_POM));
        assertNull(BuildInfo.version(loaderWith(root.resolve("bad"), BuildInfo.OWN_POM, "version=\\u00zz\n"), BuildInfo.OWN_POM),
                "a malformed escape is an IllegalArgumentException from Properties.load");
        URL missing = root.resolve("gone/pom.properties").toUri().toURL();
        ClassLoader vanished = new ClassLoader(null) {
            @Override
            public URL getResource(String name) {
                return missing;
            }
        };
        assertNull(BuildInfo.version(vanished, BuildInfo.OWN_POM), "a file that went away between lookup and read");
    }
}
