/*
 * The versions come from the jars' pom.properties and the commit from platform-pf's manifest; one that cannot be read
 * is null.
 */
package com.pingidentity.ps.oidf.platform.pf.health;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNull;

import java.io.IOException;
import java.net.URL;
import java.net.URLClassLoader;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.charset.StandardCharsets;
import java.util.jar.Attributes;
import java.util.jar.JarEntry;
import java.util.jar.JarOutputStream;
import java.util.jar.Manifest;
import java.util.Map;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

class BuildInfoTest {

    private static ClassLoader loaderWith(Path root, String path, String content) throws IOException {
        Path file = root.resolve(path);
        Files.createDirectories(file.getParent());
        Files.writeString(file, content);
        return new URLClassLoader(new URL[] {root.toUri().toURL()}, null);
    }

    @Test
    void theVersionsAreReadFromEachJarsPomProperties(@TempDir Path root) throws IOException {
        loaderWith(root, BuildInfo.OWN_POM, "version=0.5.0\n");
        ClassLoader loader = loaderWith(root, BuildInfo.PINGFEDERATE_POM, "#Generated by Maven\ngroupId=pingfederate\nversion=13.1.3.0\n");
        Map<String, Object> info = BuildInfo.read(loader);
        assertEquals("0.5.0", info.get("agentic-identity"));
        assertEquals("13.1.3.0", info.get("pingfederate"));
        assertNull(info.get("commit"), "no manifest beside the pom.properties: no commit");
        assertEquals(Runtime.version().toString(), info.get("java"));
    }

    @Test
    void theCommitIsTheBuildCommitOfPlatformPfsOwnManifest(@TempDir Path root) throws IOException {
        loaderWith(root, BuildInfo.OWN_POM, "version=0.6.0\n");
        ClassLoader loader = loaderWith(root, "META-INF/MANIFEST.MF", "Manifest-Version: 1.0\nBuild-Commit:  0123abcd \n\n");
        assertEquals("0123abcd", BuildInfo.commit(loader));
        assertEquals("0123abcd", BuildInfo.read(loader).get("commit"));
    }

    @Test
    void theCommitIsReadFromTheJarThePomIsIn(@TempDir Path root) throws IOException {
        // Another jar's manifest comes first on the loader; the commit is still platform-pf's.
        Path other = root.resolve("other.jar");
        try (JarOutputStream out = new JarOutputStream(Files.newOutputStream(other), manifest("fedcba98"))) {
            out.putNextEntry(new JarEntry("x.txt"));
        }
        Path own = root.resolve("platform-pf.jar");
        try (JarOutputStream out = new JarOutputStream(Files.newOutputStream(own), manifest("0123abcd"))) {
            out.putNextEntry(new JarEntry(BuildInfo.OWN_POM));
            out.write("version=0.6.0\n".getBytes(StandardCharsets.UTF_8));
        }
        ClassLoader loader = new URLClassLoader(new URL[] {other.toUri().toURL(), own.toUri().toURL()}, null);
        assertEquals("0123abcd", BuildInfo.commit(loader));
    }

    @Test
    void aCommitThatIsUnknownOrCannotBeReadIsNull(@TempDir Path root) throws IOException {
        assertNull(BuildInfo.commit(null));
        assertNull(BuildInfo.commit(new URLClassLoader(new URL[0], null)), "no pom.properties to find the jar by");
        assertNull(BuildInfo.commit(loaderWith(root.resolve("none"), BuildInfo.OWN_POM, "version=0.6.0\n")), "no manifest");
        for (String manifest : new String[] {"Manifest-Version: 1.0\n\n", "Manifest-Version: 1.0\nBuild-Commit: \n\n",
                "Manifest-Version: 1.0\nBuild-Commit: unknown\n\n"}) {
            Path dir = root.resolve("m" + manifest.length());
            loaderWith(dir, BuildInfo.OWN_POM, "version=0.6.0\n");
            assertNull(BuildInfo.commit(loaderWith(dir, "META-INF/MANIFEST.MF", manifest)), manifest);
        }
        URL odd = new URL("file:/a b/" + BuildInfo.OWN_POM);
        ClassLoader unparseable = new ClassLoader(null) {
            @Override
            public URL getResource(String name) {
                return odd;
            }
        };
        assertNull(BuildInfo.commit(unparseable), "a location that is not a URI");
    }

    private static Manifest manifest(String commit) {
        Manifest manifest = new Manifest();
        manifest.getMainAttributes().put(Attributes.Name.MANIFEST_VERSION, "1.0");
        manifest.getMainAttributes().putValue(BuildInfo.COMMIT, commit);
        return manifest;
    }

    @Test
    void aVersionThatCannotBeReadIsNull(@TempDir Path root) throws IOException {
        assertNull(BuildInfo.version(null, BuildInfo.OWN_POM));
        assertNull(BuildInfo.version(new URLClassLoader(new URL[0], null), BuildInfo.OWN_POM));
        assertNull(BuildInfo.version(loaderWith(root, BuildInfo.OWN_POM, "groupId=x\n"), BuildInfo.OWN_POM));
        assertNull(BuildInfo.version(loaderWith(root, BuildInfo.PINGFEDERATE_POM, "version=  \n"), BuildInfo.PINGFEDERATE_POM));
        assertNull(BuildInfo.version(loaderWith(root.resolve("bad"), BuildInfo.OWN_POM, "version=\\u00zz\n"), BuildInfo.OWN_POM),
                "a malformed escape is an IllegalArgumentException from Properties.load");
        URL missing = root.resolve("gone/pom.properties").toUri().toURL();
        ClassLoader vanished = new ClassLoader(null) {
            @Override
            public URL getResource(String name) {
                return missing;
            }
        };
        assertNull(BuildInfo.version(vanished, BuildInfo.OWN_POM), "a file that went away between lookup and read");
    }
}
