-- ldm-migration: 002-backfill-may-attrs
-- ldm-description: Populate MAY attribute lists for all 34 classes from spec docs 01 (class reference) and 06 (cryptoBinding), so validate_entry's undeclared-attribute check activates. Safe: adding MAY attrs strands nothing.
-- ldm-kind: custom
-- ldm-checksum: sha256:f241224c26c136a0605e56138dccef5ef7d18695798e505aac5061620eba8955
--
-- Generated by ldm-copilot. Tested against an ephemeral Postgres, not against
-- the target. Review before applying.
--
--   psql "$DSN" -v ON_ERROR_STOP=1 -f migrations/002-backfill-may-attrs.sql
--

BEGIN;

-- The ledger records what has been applied. Created by whichever migration
-- lands first, so no migration depends on another having run before it.
CREATE SCHEMA IF NOT EXISTS idm;
CREATE TABLE IF NOT EXISTS idm.schema_migration (
  name        text PRIMARY KEY,
  checksum    text NOT NULL,
  applied_at  timestamptz NOT NULL DEFAULT now(),
  applied_by  text NOT NULL DEFAULT current_user
);

-- >>> change
-- Verified row-by-row: if any class name here does not match the registry
-- exactly, the mismatch is a silent no-op UPDATE rather than an error — so
-- this tracks affected rows and fails loudly instead of trusting spelling.
DO $$
DECLARE total_updated int := 0; n int;
BEGIN
  UPDATE idm.object_class SET may_attrs = '{accountBSB,accountNumber,accountStatus,productRef,productType}' WHERE name = 'account';
  GET DIAGNOSTICS n = ROW_COUNT; total_updated := total_updated + n;
  UPDATE idm.object_class SET may_attrs = '{actorChain,agentAttestationRef,agentOperatorId,delegationCeiling,mayAct}' WHERE name = 'agentDelegation';
  GET DIAGNOSTICS n = ROW_COUNT; total_updated := total_updated + n;
  UPDATE idm.object_class SET may_attrs = '{serviceProfile}' WHERE name = 'application';
  GET DIAGNOSTICS n = ROW_COUNT; total_updated := total_updated + n;
  UPDATE idm.object_class SET may_attrs = '{aaguid,authenticationLevel,authenticatorType,credentialId,federatedIdpEntityId,freshUntil,stepUpFrom,stepUpReason,userVerification}' WHERE name = 'authenticationEvent';
  GET DIAGNOSTICS n = ROW_COUNT; total_updated := total_updated + n;
  UPDATE idm.object_class SET may_attrs = '{channel,deviceRef,evidenceRefs,ipAddress,policyRef,sessionRef,verifierId}' WHERE name = 'authorisationRecord';
  GET DIAGNOSTICS n = ROW_COUNT; total_updated := total_updated + n;
  UPDATE idm.object_class SET may_attrs = '{captureChannel,destructionDue,matchAlgorithm,matchScore,matchThreshold,padMethod,padResult,retentionPolicy}' WHERE name = 'biometricBindingEvidence';
  GET DIAGNOSTICS n = ROW_COUNT; total_updated := total_updated + n;
  UPDATE idm.object_class SET may_attrs = '{}' WHERE name = 'businessRole';
  GET DIAGNOSTICS n = ROW_COUNT; total_updated := total_updated + n;
  UPDATE idm.object_class SET may_attrs = '{PAN}' WHERE name = 'card';
  GET DIAGNOSTICS n = ROW_COUNT; total_updated := total_updated + n;
  UPDATE idm.object_class SET may_attrs = '{}' WHERE name = 'channel';
  GET DIAGNOSTICS n = ROW_COUNT; total_updated := total_updated + n;
  UPDATE idm.object_class SET may_attrs = '{serviceProfile,serviceRoleConstraint}' WHERE name = 'channelEntitlement';
  GET DIAGNOSTICS n = ROW_COUNT; total_updated := total_updated + n;
  UPDATE idm.object_class SET may_attrs = '{consentReceiptRef,counterpartyId,dataClusters,durationGranted,durationRequested,lawfulBasis,presentedArtefactUri,withdrawalMethod,withdrawnTimestamp}' WHERE name = 'consentRecord';
  GET DIAGNOSTICS n = ROW_COUNT; total_updated := total_updated + n;
  UPDATE idm.object_class SET may_attrs = '{archiveTimestampRef,certChainAlgorithms,cryptoPolicyRef,encAlgorithm,hashAlgorithm,hybridComposition,kemAlgorithm,keyKty,keyRef,resignDue,sigAlgorithm,signatureSet,verificationPolicy}' WHERE name = 'cryptoBinding';
  GET DIAGNOSTICS n = ROW_COUNT; total_updated := total_updated + n;
  UPDATE idm.object_class SET may_attrs = '{matchStrength,matchedAttributes,queryAttributes,screeningLists,screeningResult,sourceTransactionId}' WHERE name = 'dataSourceEvidence';
  GET DIAGNOSTICS n = ROW_COUNT; total_updated := total_updated + n;
  UPDATE idm.object_class SET may_attrs = '{chipRead,dobOnDocument,documentExpiry,documentNumberHash,dvsResult,dvsTransactionId,issuingCountry,mrzChecked,nameOnDocument,securityFeaturesChecked}' WHERE name = 'documentEvidence';
  GET DIAGNOSTICS n = ROW_COUNT; total_updated := total_updated + n;
  UPDATE idm.object_class SET may_attrs = '{description,effectiveEndDate,effectiveStartDate}' WHERE name = 'entitlement';
  GET DIAGNOSTICS n = ROW_COUNT; total_updated := total_updated + n;
  UPDATE idm.object_class SET may_attrs = '{}' WHERE name = 'externalEntry';
  GET DIAGNOSTICS n = ROW_COUNT; total_updated := total_updated + n;
  UPDATE idm.object_class SET may_attrs = '{lifecycleState,ou,trustLevel}' WHERE name = 'identity';
  GET DIAGNOSTICS n = ROW_COUNT; total_updated := total_updated + n;
  UPDATE idm.object_class SET may_attrs = '{evidenceStrength,rawArtefactRef,sourceIndependence,verificationTimestamp,verifierId}' WHERE name = 'identityEvidence';
  GET DIAGNOSTICS n = ROW_COUNT; total_updated := total_updated + n;
  UPDATE idm.object_class SET may_attrs = '{auditRef,correlationId,parentId,schemeContext,subjectId,subjectType}' WHERE name = 'identityObject';
  GET DIAGNOSTICS n = ROW_COUNT; total_updated := total_updated + n;
  UPDATE idm.object_class SET may_attrs = '{attributesProofed,biometricBindingRef,evidenceRefs,exceptionHandling,fatfReliability,fraudChecks,ipLevelPrior,ipLevelRequested,ispId,nextReproofDue,proofingType}' WHERE name = 'identityProofingRecord';
  GET DIAGNOSTICS n = ROW_COUNT; total_updated := total_updated + n;
  UPDATE idm.object_class SET may_attrs = '{boundPayload,boundTransactionHash,challengeDisplayFormat,derivedIntent,freshnessWindow,response,responseSignature,signingKeyRef}' WHERE name = 'intentRecord';
  GET DIAGNOSTICS n = ROW_COUNT; total_updated := total_updated + n;
  UPDATE idm.object_class SET may_attrs = '{iamIPID,iamIPIDData,iamIPSubType,iamIPTags,iamIPType}' WHERE name = 'involvedParty';
  GET DIAGNOSTICS n = ROW_COUNT; total_updated := total_updated + n;
  UPDATE idm.object_class SET may_attrs = '{authorizationDetailsTypes,clientName,clientSecretExpiresAt,clientSecretHash,contacts,dpopBoundAccessTokens,entityId,grantTypes,jwks,jwksUri,organisationId,policyUri,redirectUris,registrationType,requirePushedAuthorizationRequests,responseTypes,scope,sectorIdentifierUri,softwareId,softwareStatement,softwareVersion,tlsClientAuthSubjectDn,trustChain,trustMarks}' WHERE name = 'oauthClientRegistration';
  GET DIAGNOSTICS n = ROW_COUNT; total_updated := total_updated + n;
  UPDATE idm.object_class SET may_attrs = '{authenticationEventRef,authorizationDetails,consentRef,entitlementRef,extendedAttributes,grantContext,hashedRefreshTokenValue,resourceAuthorisationRefs,scope,uniqueUserIdentifier,updatedTimestamp}' WHERE name = 'oauthGrant';
  GET DIAGNOSTICS n = ROW_COUNT; total_updated := total_updated + n;
  UPDATE idm.object_class SET may_attrs = '{accountIdentifiers,actions,audience,authorizationDetail,constraints,notAfter,notBefore}' WHERE name = 'protectedResourceAuthorisation';
  GET DIAGNOSTICS n = ROW_COUNT; total_updated := total_updated + n;
  UPDATE idm.object_class SET may_attrs = '{relatedInvolvedParty}' WHERE name = 'relatedInvolvedParty';
  GET DIAGNOSTICS n = ROW_COUNT; total_updated := total_updated + n;
  UPDATE idm.object_class SET may_attrs = '{}' WHERE name = 'resource';
  GET DIAGNOSTICS n = ROW_COUNT; total_updated := total_updated + n;
  UPDATE idm.object_class SET may_attrs = '{}' WHERE name = 'resourceRole';
  GET DIAGNOSTICS n = ROW_COUNT; total_updated := total_updated + n;
  UPDATE idm.object_class SET may_attrs = '{}' WHERE name = 'role';
  GET DIAGNOSTICS n = ROW_COUNT; total_updated := total_updated + n;
  UPDATE idm.object_class SET may_attrs = '{aal,apiOperation,productRef}' WHERE name = 'serviceProfile';
  GET DIAGNOSTICS n = ROW_COUNT; total_updated := total_updated + n;
  UPDATE idm.object_class SET may_attrs = '{serviceProfile}' WHERE name = 'serviceRole';
  GET DIAGNOSTICS n = ROW_COUNT; total_updated := total_updated + n;
  UPDATE idm.object_class SET may_attrs = '{channel}' WHERE name = 'serviceUser';
  GET DIAGNOSTICS n = ROW_COUNT; total_updated := total_updated + n;
  UPDATE idm.object_class SET may_attrs = '{}' WHERE name = 'structuralEntitlement';
  GET DIAGNOSTICS n = ROW_COUNT; total_updated := total_updated + n;
  UPDATE idm.object_class SET may_attrs = '{disclosedClaims,holderBindingMethod,holderBindingResult,issuerAccreditation,nonce,presentationHash,presentationProtocol,statusCheckMethod,statusCheckResult,trustPathRef}' WHERE name = 'verifiablePresentationEvidence';
  GET DIAGNOSTICS n = ROW_COUNT; total_updated := total_updated + n;
  IF total_updated <> 34 THEN
    RAISE EXCEPTION 'expected to update exactly 34 classes, updated % — a class name here does not match the registry', total_updated;
  END IF;
END $$;
-- <<< change

INSERT INTO idm.schema_migration (name, checksum)
VALUES ('002-backfill-may-attrs', 'sha256:f241224c26c136a0605e56138dccef5ef7d18695798e505aac5061620eba8955')
ON CONFLICT (name) DO UPDATE SET checksum = EXCLUDED.checksum, applied_at = now();

COMMIT;
