"""tools/config-reference.py on made-up reactors: a page's header and rows, the README's generated list, the
extended-properties contract, --check against a missing, changed or stale file, the catalogue problems it refuses,
the A-Z index, and the repository as it is."""
import io
import json
import os
import tempfile
import unittest
from contextlib import redirect_stderr, redirect_stdout

from _tools import load

ref = load("config-reference.py")

REPO = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
README_TEXT = "# Configuration reference\n\nBy hand.\n\n" + ref.BEGIN + "\nold list\n" + ref.END + "\n\nAfter.\n"


def entry(name, kind="env", **over):
    e = {"name": name, "kind": kind, "type": "string", "default": None, "description": "What it does",
         "when_wrong": {"effect": "not-checked", "detail": "Read as given"}, "profile": "any", "security": False,
         "sources": [{"from": kind, "name": name}] if kind in ("env", "system-property", "init-param") else [],
         "aliases": [], "file": False}
    e.update(over)
    return e


def catalogue(component, module, settings, removed=(), families=()):
    return {"format": 1, "component": component, "module": module, "package": "x.y", "families": list(families),
            "settings": settings, "removed": list(removed)}


class Tree:
    """A reactor on disk: a root pom, modules with catalogues, docs/configuration/README.md."""

    def __init__(self, test, readme=README_TEXT):
        self.dir = tempfile.TemporaryDirectory()
        test.addCleanup(self.dir.cleanup)
        self.root = self.dir.name
        self.modules = []
        if readme is not None:
            self.write(ref.README, readme)

    def module(self, path, *docs):
        self.modules.append(path)
        for doc in docs:
            self.write(os.path.join(path, "src/main/resources/META-INF/oidf-settings", doc["component"] + ".json"),
                       json.dumps(doc))
        self.write("pom.xml", "<project><modules>" + "".join(f"<module>{m}</module>" for m in self.modules)
                   + "</modules></project>")
        return self

    def write(self, rel, text):
        full = os.path.join(self.root, rel)
        os.makedirs(os.path.dirname(full), exist_ok=True)
        with open(full, "w", encoding="utf-8") as f:
            f.write(text)

    def read(self, rel):
        with open(os.path.join(self.root, rel), encoding="utf-8") as f:
            return f.read()

    def run(self, *args):
        out, err = io.StringIO(), io.StringIO()
        with redirect_stdout(out), redirect_stderr(err):
            status = ref.main(["--root", self.root, *args])
        return status, out.getvalue(), err.getvalue()


PDP = catalogue("pdp", "libs/a", [
    entry("OIDF_PDP_MODE", type="choice", default="local", choices=["off", "local", "authzen"],
          sources=[{"from": "system-property", "name": "oidf.pdp.mode"}, {"from": "env", "name": "OIDF_PDP_MODE"}],
          aliases=[{"name": "OIDF_OLD_MODE", "sources": [{"from": "env", "name": "OIDF_OLD_MODE"}]}],
          when_wrong={"effect": "doesnt-start", "detail": "Anything else"}, security=True),
    entry("OIDF_PDP_TOKEN", type="secret", file=True, security=True, profile="required-in-production",
          when_wrong={"effect": "per-request", "detail": "Every call is refused"}),
    entry("OIDF_PDP_TIMEOUT_MS", type="millis", default=3000, min=1, max=60000,
          when_wrong={"effect": "first-request", "detail": "A | pipe"}),
    entry("OIDF_PDP_CACHE", type="int", default=0, min=0, max=2147483647, profile="forbidden-in-production"),
    entry("signingAlgorithm", kind="init-param", default="RS256", profile="accepted-risk:weak-thing"),
    entry("Request timeout (ms)", kind="plugin-field", type="long", default=5000, min=-2 ** 63, max=2 ** 63 - 1),
    entry("status", kind="extended-property"),
], removed=[{"name": "OIDF_PDP_STRICT", "from": "env", "replacement": "OIDF_PDP_MODE", "release": "0.4.0"},
            {"name": "OIDF_PDP_GONE", "from": "env", "replacement": None, "release": "0.3.0"}],
    families=["OIDF_PDP_"])
LATER = catalogue("later", "libs/b", [entry("attestation_x", kind="extended-property"),
                                      entry("OIDF_LATER", type="bool", default=True)])


class PageTest(unittest.TestCase):
    def setUp(self):
        self.tree = Tree(self).module("libs/a", PDP).module("libs/b", LATER)
        status, _out, err = self.tree.run()
        self.assertEqual(0, status, err)
        self.page = self.tree.read("docs/configuration/pdp.md")

    def test_the_header_names_the_catalogue_and_says_the_page_is_generated(self):
        lines = self.page.splitlines()
        self.assertEqual("# pdp", lines[0])
        self.assertIn("<!-- Generated by tools/config-reference.py from libs/a/src/main/resources/META-INF/oidf-settings/"
                      "pdp.json. Do not edit", lines[2])
        self.assertIn("[pdp.json](../../libs/a/src/main/resources/META-INF/oidf-settings/pdp.json)", self.page)
        self.assertIn("Families: `OIDF_PDP_`.", self.page)
        self.assertIn("| Setting | Default | What it does | When it's wrong | Profile | Security |", self.page)

    def test_rows_come_in_the_catalogue_order(self):
        names = [line.split("`")[1] for line in self.page.splitlines() if line.startswith("| `")]
        self.assertEqual(["OIDF_PDP_MODE", "OIDF_PDP_TOKEN", "OIDF_PDP_TIMEOUT_MS", "OIDF_PDP_CACHE", "signingAlgorithm",
                          "Request timeout (ms)", "status", "OIDF_PDP_STRICT", "OIDF_PDP_GONE"], names)

    def test_a_setting_read_from_several_places_names_them_in_order_with_its_superseded_names(self):
        self.assertIn(
            "\n| `OIDF_PDP_MODE` (system property `oidf.pdp.mode`, then env `OIDF_PDP_MODE`); superseded, still read:"
            " `OIDF_OLD_MODE` | `local`; one of `off`, `local`, `authzen` | What it does | **Doesn't start**: Anything"
            " else | Any | Yes |\n", self.page)

    def test_a_secret_from_a_file_a_range_and_a_pipe(self):
        self.assertIn("\n| `OIDF_PDP_TOKEN`; or from the file `OIDF_PDP_TOKEN_FILE` names | Unset; a secret, never shown"
                      " | What it does | **Per request**: Every call is refused | Required in production | Yes |\n",
                      self.page)
        self.assertIn("| `OIDF_PDP_TIMEOUT_MS` | `3000`; milliseconds, 1 to 60000 | What it does | **First request**: A \\|"
                      " pipe | Any | No |", self.page)
        self.assertIn("| `OIDF_PDP_CACHE` | `0`; a whole number, at least 0 | What it does | **Not checked**: Read as"
                      " given | Not in production | No |", self.page)

    def test_the_kinds_pingfederate_supplies_and_an_accepted_risk(self):
        self.assertIn("| `signingAlgorithm` (init-param) | `RS256` | What it does | **Not checked**: Read as given | In"
                      " production only as accepted risk `weak-thing` | No |", self.page)
        self.assertIn("| `Request timeout (ms)` (plugin field) | `5000`; a whole number |", self.page)
        self.assertIn("| `status` (extended property) | Unset |", self.page)
        self.assertIn("| `OIDF_LATER` | `true` |", self.tree.read("docs/configuration/later.md"))

    def test_removed_names(self):
        self.assertIn("## Removed", self.page)
        self.assertIn("| `OIDF_PDP_STRICT` | env | `OIDF_PDP_MODE` | 0.4.0 |", self.page)
        self.assertIn("| `OIDF_PDP_GONE` | env | Nothing | 0.3.0 |", self.page)
        self.assertNotIn("## Removed", self.tree.read("docs/configuration/later.md"))

    def test_the_readme_list_is_replaced_and_the_rest_kept(self):
        readme = self.tree.read(ref.README)
        self.assertTrue(readme.startswith("# Configuration reference\n\nBy hand.\n\n" + ref.BEGIN))
        self.assertTrue(readme.endswith(ref.END + "\n\nAfter.\n"))
        self.assertNotIn("old list", readme)
        self.assertIn("| [pdp](pdp.md) | `libs/a` | `x.y` | 7 |\n| [later](later.md) | `libs/b` | `x.y` | 2 |", readme)

    def test_the_extended_properties_contract(self):
        doc = json.loads(self.tree.read(ref.EXTENDED))
        self.assertEqual(["_comment", "extended_properties"], list(doc))
        self.assertEqual(ref.EXTENDED_COMMENT, doc["_comment"])
        self.assertEqual(["status", "attestation_x"], doc["extended_properties"])
        self.assertTrue(self.tree.read(ref.EXTENDED).endswith("]\n}\n"))

    def test_a_code_span_holding_a_backtick(self):
        self.assertEqual("``a`b``", ref.code("a`b"))
        self.assertEqual("`` `a ``", ref.code("`a"))


class CheckTest(unittest.TestCase):
    def tree(self):
        tree = Tree(self).module("libs/a", PDP).module("libs/b", LATER)
        self.assertEqual(0, tree.run()[0])
        return tree

    def test_current_files_pass_and_a_second_write_changes_nothing(self):
        tree = self.tree()
        status, out, _err = tree.run("--check")
        self.assertEqual(0, status)
        self.assertIn("current: 2 component page(s)", out)
        self.assertIn("0 file(s) changed", tree.run()[1])

    def test_a_changed_missing_or_stale_file_fails_and_is_named(self):
        tree = self.tree()
        tree.write("docs/configuration/pdp.md", tree.read("docs/configuration/pdp.md") + "by hand\n")
        os.remove(os.path.join(tree.root, ref.EXTENDED))
        tree.write("docs/configuration/gone.md", "# gone\n\n" + ref.MARK + " from x. -->\n")
        tree.write("docs/configuration/notes.md", "# written by hand, not generated\n")
        status, _out, err = tree.run("--check")
        self.assertEqual(1, status)
        self.assertIn("docs/configuration/pdp.md is not what the catalogues generate", err)
        self.assertIn("docs/extended-properties.json is missing", err)
        self.assertIn("docs/configuration/gone.md is generated from a catalogue that no longer exists", err)
        self.assertNotIn("notes.md", err)
        self.assertIn("3 generated file(s) not current", err)
        tree.run()
        self.assertFalse(os.path.exists(os.path.join(tree.root, "docs/configuration/gone.md")))
        self.assertTrue(os.path.exists(os.path.join(tree.root, "docs/configuration/notes.md")))
        self.assertEqual(0, tree.run("--check")[0])

    def test_a_readme_without_its_markers_fails(self):
        tree = self.tree()
        tree.write(ref.README, "# Configuration reference\n")
        status, _out, err = tree.run("--check")
        self.assertEqual(1, status)
        self.assertIn("has no " + ref.BEGIN, err)
        os.remove(os.path.join(tree.root, ref.README))
        self.assertIn(f"{ref.README} is missing", tree.run("--check")[2])

    def test_the_index_is_written_only_when_asked(self):
        tree = self.tree()
        index = os.path.join(tree.root, "index.md")
        self.assertEqual(0, tree.run("--check", "--index", index)[0])
        with open(index, encoding="utf-8") as f:
            text = f.read()
        names = [line.split("`")[1] for line in text.splitlines() if line.startswith("| `")]
        self.assertEqual(sorted(names, key=str.lower), names)
        self.assertIn("| `oidf.pdp.mode` | system property | [pdp](pdp.md) |", text)
        self.assertIn("| `OIDF_OLD_MODE` | env, superseded by OIDF_PDP_MODE | [pdp](pdp.md) |", text)
        self.assertFalse([n for n in os.listdir(os.path.join(tree.root, "docs/configuration")) if "index" in n])


class RefusedTest(unittest.TestCase):
    def refused(self, *docs):
        tree = Tree(self)
        for i, doc in enumerate(docs):
            tree.module(f"libs/m{i}", doc)
        status, _out, err = tree.run()
        self.assertEqual(1, status)
        self.assertFalse(os.path.exists(os.path.join(tree.root, ref.EXTENDED)), "nothing is written")
        return err

    def test_defaults_the_type_refuses(self):
        cases = {
            "outside": entry("OIDF_X", type="int", default=5, min=0, max=3),
            "not whole": entry("OIDF_X", type="seconds", default="soon", min=0, max=3),
            "not a choice": entry("OIDF_X", type="choice", default="maybe", choices=["yes", "no"]),
            "not https": entry("OIDF_X", type="https-url", default="http://a.example"),
            "not an object": entry("OIDF_X", type="json-object", default="[]"),
            "no words": entry("OIDF_X", type="words", default=" , "),
            "not a switch": entry("OIDF_X", type="bool", default="yes"),
            "a fraction": entry("OIDF_X", type="long", default=1.5, min=0, max=3),
        }
        for name, bad in cases.items():
            with self.subTest(name):
                self.assertIn("OIDF_X: the default is refused", self.refused(catalogue("c", "libs/m0", [bad])))

    def test_defaults_the_java_loader_takes_as_text(self):
        # Catalogue.parse reads a default as text - true, false and numbers as JSON writes them - and then parses it.
        tree = Tree(self).module("libs/m0", catalogue("c", "libs/m0", [
            entry("OIDF_A", type="bool", default="TRUE"), entry("OIDF_B", default=3), entry("OIDF_C", default=False),
            entry("OIDF_D", type="int", default="7", min=0, max=9)]))
        self.assertEqual(0, tree.run()[0])
        page = tree.read("docs/configuration/c.md")
        for cells in ("| `OIDF_A` | `TRUE` |", "| `OIDF_B` | `3` |", "| `OIDF_C` | `false` |", "| `OIDF_D` | `7`;"):
            self.assertIn(cells, page)

    def test_shapes_a_page_cannot_print(self):
        err = self.refused(catalogue("c", "libs/m0", [
            entry("OIDF_A", type="int", default=1, min=3, max=0),
            entry("OIDF_B", type="int", default=1, min=0, max=2 ** 31),
            entry("OIDF_C", type="choice", default="a", choices=["a", "A"]),
            entry("OIDF_D", description="two\nlines"),
            entry("OIDF_E", when_wrong={"effect": "not-checked", "detail": "two\nlines"}),
        ], removed=[{"name": "OIDF_OLD", "from": "env", "replacement": "OIDF_NOWHERE", "release": "0.4.0"}]))
        self.assertIn("OIDF_A: min is more than max", err)
        self.assertIn("OIDF_B: min and max are whole numbers", err)
        self.assertIn("OIDF_C: choices are words", err)
        self.assertIn("OIDF_D: description is one line", err)
        self.assertIn("OIDF_E: when_wrong.detail is one line", err)
        self.assertIn("removed OIDF_OLD's replacement OIDF_NOWHERE is not a setting of this catalogue", err)

    def test_a_component_in_two_modules_and_a_catalogue_the_scan_refuses(self):
        err = self.refused(catalogue("c", "libs/m0", [entry("OIDF_A")]), catalogue("c", "libs/m1", [entry("OIDF_B")]))
        self.assertIn("component c is catalogued by", err)
        err = self.refused(dict(catalogue("c", "libs/m0", [entry("OIDF_A")]), extra=1))
        self.assertIn("missing or unknown", err)


class RepositoryTest(unittest.TestCase):
    def test_the_committed_files_are_current(self):
        out, err = io.StringIO(), io.StringIO()
        with redirect_stdout(out), redirect_stderr(err):
            status = ref.main(["--root", REPO, "--check"])
        self.assertEqual(0, status, err.getvalue())

    def test_the_contract_lists_every_catalogued_extended_property(self):
        with open(os.path.join(REPO, ref.EXTENDED), encoding="utf-8") as f:
            names = json.load(f)["extended_properties"]
        self.assertEqual(len(names), len(set(names)))
        for name in ("status", "trust_chain", "federation_registration_expires_at", "attestation_required",
                     "attestation_pop_max_age", "trust_chain_request_max_age", "attestation_issuer",
                     "attestation_evidence"):
            self.assertIn(name, names)
        catalogued = [e["name"] for c in ref.load(REPO) for e in c.entries if e["kind"] == "extended-property"]
        self.assertEqual(catalogued, names)

    def test_every_page_is_linked_from_the_readme(self):
        with open(os.path.join(REPO, ref.README), encoding="utf-8") as f:
            readme = f.read()
        for c in ref.load(REPO):
            self.assertIn(f"[{c.component}]({c.component}.md)", readme)


if __name__ == "__main__":
    unittest.main()
