# Copy to secret.yaml (git-ignored), fill in, and `kubectl apply -f secret.yaml`.
# The DevOps credentials fetch a ~7-day evaluation license at container start (17-check-license.sh in
# the base image). NEVER commit the filled file.
apiVersion: v1
kind: Secret
metadata:
  name: pf-devops-license
  namespace: pf
type: Opaque
stringData:
  PING_IDENTITY_DEVOPS_USER: "<devops email>"
  PING_IDENTITY_DEVOPS_KEY: "<devops key>"
