#!/usr/bin/env python3
"""The configuration reference and docs/extended-properties.json, generated from the settings catalogues (plan
item ST-4).

  tools/config-reference.py                 write every generated file under the current directory
  tools/config-reference.py --check         exit 1 naming each generated file that is missing, stale or not current
  tools/config-reference.py --root DIR
  tools/config-reference.py --index FILE    also write the A-Z index of every name to FILE (not committed)

What it reads: every settings catalogue of the reactor - src/main/resources/META-INF/oidf-settings/<component>.json
in each module of the root pom's <modules> (docs/development/settings-catalogue.md) - through tools/settings-scan.py's
loader, so the scan and the reference read the same files the same way. What it writes:

  docs/configuration/<component>.md   one page per component: a header naming the catalogue it came from, then the
                                      house table (docs/development/style-guide.md#settings) with two more columns,
                                      Setting | Default | What it does | When it's wrong | Profile | Security, in the
                                      catalogue's order, and the component's removed names when it has any; the
                                      Profile column names the values the class acts on (the catalogue's governed
                                      member, or the default rule) and the page names the components a violation
                                      refuses
  docs/configuration/README.md        only the list of components between its GENERATED markers; the rest of the
                                      page is written by hand
  docs/extended-properties.json       every extended-property entry of every catalogue, in module order and then
                                      catalogue order, under the _comment below: the contract a consumer's Terraform
                                      is diffed against

Pages come out in a stable order and a stable form, so --check can compare bytes. A page in docs/configuration
that carries the generated header but no catalogue writes any more is stale: --check names it and a write deletes
it. The settings A-Z index is generated on demand and never committed (programme plan, decision 18): it moves with
every catalogue, and a committed copy would be a conflict in every parallel pull request.

Before it writes anything it checks what the scan's shape check leaves to the Java loader and a page would
otherwise print wrong: a default that does not parse as its type or lies outside its range, a range whose minimum
is above its maximum, a choice listed twice, text that is not one line, a removed name whose replacement is not a
setting of its catalogue, and a component catalogued twice. The Java loader (platform.settings' Catalogue.parse)
remains the full check.

Standard library only. Exit status: 0 when written or current, 1 when --check finds a difference or a catalogue is
refused, 2 for a usage error.
"""
import argparse
import importlib.util
import json
import math
import os
import re
import sys
import urllib.parse

_spec = importlib.util.spec_from_file_location(
    "settings_scan", os.path.join(os.path.dirname(os.path.abspath(__file__)), "settings-scan.py"))
scan = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(scan)

PAGES = "docs/configuration"
README = "docs/configuration/README.md"
EXTENDED = "docs/extended-properties.json"
TOOL = "tools/config-reference.py"
MARK = "<!-- Generated by tools/config-reference.py"
BEGIN = "<!-- GENERATED: the components, by tools/config-reference.py -->"
END = "<!-- END GENERATED -->"

EXTENDED_COMMENT = [
    "The PingFederate extended-property names the OIDF modules read from or write onto an OAuth client.",
    "PF drops an extended parameter whose name is not declared server-side - silently, when the",
    "module stores the client in-process - so every PF that runs these modules must declare all of them,",
    "typically as a pingfederate_extended_properties resource in that deployment's own Terraform",
    "(conformance/terraform/extended-properties.tf reads this file). A registration whose client comes back",
    "without 'status' is refused and the client disabled; a per-client attestation or chain setting",
    "that PF dropped is simply not applied (F-0041).",
    "",
    "This file is the contract between the capability and whoever deploys it. It is generated by",
    "tools/config-reference.py from the extended-property entries of the settings catalogues",
    "(META-INF/oidf-settings/*.json), and the Build workflow's lint job fails when it is not current.",
    "The scan (tools/settings-scan.py) holds the catalogues to the code both ways, and",
    "FederationClientParamsTest holds FederationClientParams.EXTENDED_PARAM_NAMES to pf-integration's",
    "catalogue, so it cannot drift from the code. Consuming repos diff their own extended-properties.tf",
    "against this file in their CI.",
    "",
    "It replaces a test that read ../../deploy/pingfederate/terraform/extended-properties.tf behind an",
    "assumeTrue(exists) guard. That worked only while the deploy tree lived in this repo; once it moved",
    "the guard would have skipped, and the check would have passed forever without checking anything.",
    "",
    "'status' is load-bearing: it is the only thing distinguishing a client this module registered from",
    "one an administrator created, and both registration paths refuse to touch a client that lacks it.",
]

KIND_LABEL = {"env": "env", "system-property": "system property", "init-param": "init-param",
              "plugin-field": "plugin field", "extended-property": "extended property"}
EFFECT_LABEL = {"doesnt-start": "Doesn't start", "first-request": "First request", "per-request": "Per request",
                "not-checked": "Not checked"}
INT_RANGE = (-2 ** 31, 2 ** 31 - 1)
LONG_RANGE = (-2 ** 63, 2 ** 63 - 1)
TYPE_PHRASE = {"int": "a whole number", "long": "a whole number", "seconds": "seconds", "millis": "milliseconds",
               "https-url": "an https URL", "url": "an http or https URL", "json-object": "a JSON object",
               "words": "a list", "path": "a file path", "secret": "a secret, never shown"}
PROFILE_LABEL = {"any": "Any", "forbidden-in-production": "Not in production",
                 "required-in-production": "Required in production"}


class Refused(Exception):
    """Catalogues the reference cannot be generated from; carries the problems."""


# --- checks the pages depend on --------------------------------------------------------------------------------

def default_text(value):
    """A default as text, as the Java loader takes it: a string as it is, true, false or a number as JSON writes it."""
    if value is None or isinstance(value, str):
        return value
    return json.dumps(value)


def default_problem(entry):
    """Why the default does not parse as the entry's type, or None."""
    text, kind = default_text(entry["default"]), entry["type"]
    if text is None:
        return None
    if kind == "bool" and text.lower() not in ("true", "false"):
        return f"{text!r} is not true or false"
    if kind in scan.RANGED:
        if not re.fullmatch(r"-?[0-9]+", text.strip()):
            return f"{text!r} is not a whole number"
        number = int(text)
        if not entry["min"] <= number <= entry["max"]:
            return f"{number} is outside {entry['min']} to {entry['max']}"
    if kind == "choice" and text.strip().lower() not in {c.lower() for c in entry["choices"]}:
        return f"{text!r} is not one of the choices"
    if kind in ("https-url", "url"):
        url = urllib.parse.urlsplit(text.strip())
        if url.scheme not in (("https",) if kind == "https-url" else ("http", "https")) or not url.hostname:
            return f"{text!r} is not an absolute {'https' if kind == 'https-url' else 'http or https'} URL with a host"
    if kind == "json-object":
        try:
            parsed = json.loads(text)
        except ValueError:
            parsed = None
        if not isinstance(parsed, dict):
            return f"{text!r} is not a JSON object"
    if kind == "words" and not [w for w in re.split(r"[\s,]+", text) if w]:
        return "a list of nothing"
    return None


def check(catalogues):
    """What the pages depend on, beyond the scan's shape check; a list of problems."""
    problems = []
    components = {}
    for c in catalogues:
        components.setdefault(c.component, []).append(c.path)
        where = c.path
        settings = {e["name"] for e in c.entries}
        for e in c.entries:
            at = f"{where}: {e['name']}"
            for member in ("name", "description"):
                if not isinstance(e[member], str) or not e[member].strip() or e[member] != e[member].strip() \
                        or any(ord(ch) < 0x20 or ord(ch) == 0x7f for ch in e[member]):
                    problems.append(f"{at}: {member} is one line of text with no spaces around it")
            detail = e["when_wrong"]["detail"]
            if not isinstance(detail, str) or not detail.strip() or any(ord(ch) < 0x20 for ch in detail):
                problems.append(f"{at}: when_wrong.detail is one line of text")
            if e["type"] in scan.RANGED:
                floor, ceiling = INT_RANGE if e["type"] == "int" else LONG_RANGE
                bounds = (e["min"], e["max"])
                if not all(isinstance(b, int) and not isinstance(b, bool) and floor <= b <= ceiling for b in bounds):
                    problems.append(f"{at}: min and max are whole numbers from {floor} to {ceiling}")
                    continue
                if e["min"] > e["max"]:
                    problems.append(f"{at}: min is more than max")
                    continue
            if e["type"] == "words" and isinstance(e["description"], str) and "separated" not in e["description"]:
                # Legacy readers split on commas only, platform.settings on spaces or commas: the page cannot know
                # which, so the description says (comma-separated, space-separated, space- or comma-separated).
                problems.append(f"{at}: a list's description says how it is separated")
            if e["type"] == "choice":
                folded = [c2.lower() if isinstance(c2, str) else c2 for c2 in e["choices"]]
                if not folded or len(set(folded)) != len(folded) or not all(isinstance(c2, str) for c2 in folded):
                    problems.append(f"{at}: choices are words, at least one, none listed twice in any case")
                    continue
            if isinstance(e["default"], float) and not math.isfinite(e["default"]):
                problems.append(f"{at}: the default is not a number JSON can hold")
                continue
            why = default_problem(e)
            if why:
                problems.append(f"{at}: the default is refused: {why}")
        for gone in c.removed:
            if gone["replacement"] is not None and gone["replacement"] not in settings:
                problems.append(f"{where}: removed {gone['name']}'s replacement {gone['replacement']} is not a setting"
                                " of this catalogue")
    for component, paths in sorted(components.items()):
        if len(paths) > 1:
            problems.append(f"component {component} is catalogued by {', '.join(paths)}; one module owns it")
    return problems


def load(root):
    """The reactor's catalogues in module order, then file order; Refused when one cannot be used."""
    catalogues, problems = scan.load_catalogues(root, scan.modules_of(root))
    problems += check(catalogues)
    if problems:
        raise Refused(problems)
    table = scan.components_table(root) or {}
    for c in catalogues:
        # The scan's Catalogue does not keep the families, which a page prints.
        with open(os.path.join(root, c.path), encoding="utf-8") as f:
            c.families = json.load(f)["families"]
        c.refuses = c.components if c.components is not None else table.get(c.component, [])
    return catalogues


# --- rendering -------------------------------------------------------------------------------------------------

def cell(text):
    """Text for a table cell: a pipe would end the cell."""
    return text.replace("|", "\\|")


def code(text):
    """An inline code span, wide enough for any backticks the text holds."""
    fence = "`" * (max((len(run) for run in re.findall(r"`+", text)), default=0) + 1)
    pad = " " if text.startswith("`") or text.endswith("`") else ""
    return f"{fence}{pad}{text}{pad}{fence}"


def sources_text(sources):
    return ", then ".join(f"{KIND_LABEL[s['from']]} {code(s['name'])}" for s in sources)


def setting_cell(entry):
    kind, name = entry["kind"], entry["name"]
    out = code(name)
    if kind not in scan.SOURCE_KINDS:
        return out + f" ({KIND_LABEL[kind]})"
    if entry["sources"] != [{"from": kind, "name": name}]:
        out += f" ({sources_text(entry['sources'])})"
    elif kind != "env":
        out += f" ({KIND_LABEL[kind]})"
    for alias in entry["aliases"]:
        out += f"; superseded, still read: {code(alias['name'])}"
        if len(alias["sources"]) > 1 or alias["sources"][0]["from"] != kind:
            out += f" ({sources_text(alias['sources'])})"
    if entry["file"]:
        out += "; or from the file " + " or ".join(code(scan.file_variant(s["from"], s["name"])) for s in entry["sources"]) \
               + " names"
    return out


def range_text(entry):
    floor, ceiling = INT_RANGE if entry["type"] == "int" else LONG_RANGE
    low, high = entry["min"], entry["max"]
    if (low, high) == (floor, ceiling):
        return None
    if high == ceiling:
        return f"at least {low}"
    if low == floor:
        return f"at most {high}"
    return f"{low} to {high}"


def default_cell(entry):
    value = entry["default"]
    out = "Unset" if value is None else code(default_text(value))
    notes = []
    if entry["type"] in TYPE_PHRASE:
        notes.append(TYPE_PHRASE[entry["type"]])
    if entry["type"] in scan.RANGED:
        span = range_text(entry)
        if span:
            notes.append(span)
    if entry["type"] == "choice":
        notes.append("one of " + ", ".join(code(c) for c in entry["choices"]))
    return out + ("; " + ", ".join(notes) if notes else "")


def governed_text(entry):
    """What the profile class acts on, in words, as platform.settings' Governed describes it; None for any and required."""
    governed = scan.governed_of(entry)
    if governed is None:
        return None
    form, values = governed
    if form == "values":
        return " or ".join(code(v) for v in values)
    if form == "schemes":
        unless = scan.unless_set_of(entry)
        return "a " + " or ".join(code(v + "://") for v in values) + " URL" + (
            " while " + " and ".join(code(u) for u in unless) + " " + ("is" if len(unless) == 1 else "are") + " unset"
            if unless else "")
    return "any value"


def profile_cell(entry):
    profile = entry["profile"]
    governed = governed_text(entry)
    own = "; refuses " + ", ".join(code(c) for c in entry["components"]) if entry.get("components") else ""
    if profile.startswith("accepted-risk:"):
        return "In production only as accepted risk " + code(profile.partition(":")[2]) + ": " + governed + own
    if governed is not None:
        return PROFILE_LABEL[profile] + ": " + governed + own
    return PROFILE_LABEL[profile] + own


def row(entry):
    wrong = entry["when_wrong"]
    cells = [setting_cell(entry), default_cell(entry), entry["description"],
             f"**{EFFECT_LABEL[wrong['effect']]}**: {wrong['detail']}", profile_cell(entry),
             "Yes" if entry["security"] else "No"]
    return "| " + " | ".join(cell(c) for c in cells) + " |"


def page(catalogue):
    source = catalogue.path.replace(os.sep, "/")
    link = "../../" + source
    lines = [
        f"# {catalogue.component}",
        "",
        f"{MARK} from {source}. Do not edit: change the catalogue, then run python3 {TOOL}. -->",
        "",
        f"The settings of the `{catalogue.component}` component of `{catalogue.module}`, read by package"
        f" `{catalogue.package}`: generated from its catalogue, [{os.path.basename(source)}]({link}), by"
        f" `{TOOL}`, and checked in CI. [How to read a row](README.md#reading-a-row).",
    ]
    if catalogue.families:
        lines += ["", "Families: " + ", ".join(code(f) for f in catalogue.families) + ". A name under one of these that no"
                  " catalogue declares is an unknown key."]
    refuses = getattr(catalogue, "refuses", [])
    lines += ["", "Under the production profile a violation by one of these settings refuses "
              + (", ".join(code(c) for c in refuses) if refuses else "no component")
              + " ([components](../development/settings-catalogue.md#components))."]
    lines += ["", "| Setting | Default | What it does | When it's wrong | Profile | Security |",
              "|---|---|---|---|---|---|"]
    lines += [row(e) for e in catalogue.entries]
    if catalogue.removed:
        lines += ["", "## Removed", "",
                  "Set in the source it was read from, a removed name is refused, naming what replaces it.", "",
                  "| Setting | Read from | Instead | Removed in |", "|---|---|---|---|"]
        for gone in catalogue.removed:
            instead = code(gone["replacement"]) if gone["replacement"] else "Nothing"
            lines.append("| " + " | ".join(cell(c) for c in (code(gone["name"]), KIND_LABEL[gone["from"]], instead,
                                                                 gone["release"])) + " |")
    return "\n".join(lines) + "\n"


def components_block(catalogues):
    lines = [BEGIN, "", "| Component | Module | Package | Settings |", "|---|---|---|---|"]
    for c in catalogues:
        lines.append(f"| [{c.component}]({c.component}.md) | `{c.module}` | `{c.package}` | {len(c.entries)} |")
    lines += ["", END]
    return "\n".join(lines)


def readme(current, catalogues):
    """README.md with its generated block replaced; None when the markers are missing."""
    start, end = current.find(BEGIN), current.find(END)
    if start < 0 or end < start:
        return None
    return current[:start] + components_block(catalogues) + current[end + len(END):]


def extended_properties(catalogues):
    names = [e["name"] for c in catalogues for e in c.entries if e["kind"] == "extended-property"]
    return json.dumps({"_comment": EXTENDED_COMMENT, "extended_properties": names}, indent=2) + "\n"


def index(catalogues):
    """The A-Z index: every name an operator can set, with its component and how it is read."""
    rows = []
    for c in catalogues:
        for e in c.entries:
            names = [(e["name"], KIND_LABEL[e["kind"]])]
            names += [(s["name"], KIND_LABEL[s["from"]]) for s in e["sources"] if s["name"] != e["name"]]
            names += [(s["name"], KIND_LABEL[s["from"]] + f", superseded by {e['name']}")
                      for a in e["aliases"] for s in a["sources"]]
            for name, how in names:
                rows.append((name.lower(), name, how, c.component))
    lines = ["# Settings, A to Z", "", f"Generated by `{TOOL} --index`; not committed.", "",
             "| Name | Read as | Component |", "|---|---|---|"]
    lines += [f"| {cell(code(name))} | {cell(how)} | [{component}]({component}.md) |"
              for _key, name, how, component in sorted(set(rows))]
    return "\n".join(lines) + "\n"


# --- write and check -------------------------------------------------------------------------------------------

def expected(root, catalogues):
    """{relative path: content} of every generated file; the README only when it has its markers."""
    out = {EXTENDED: extended_properties(catalogues)}
    for c in catalogues:
        out[f"{PAGES}/{c.component}.md"] = page(c)
    path = os.path.join(root, README)
    if os.path.isfile(path):
        with open(path, encoding="utf-8") as f:
            current = f.read()
        text = readme(current, catalogues)
        out[README] = text if text is not None else current
    return out


def generated_pages(root):
    """The pages in docs/configuration that carry the generated header."""
    folder = os.path.join(root, PAGES)
    found = []
    if os.path.isdir(folder):
        for name in sorted(os.listdir(folder)):
            path = os.path.join(folder, name)
            if name.endswith(".md") and os.path.isfile(path):
                with open(path, encoding="utf-8") as f:
                    if MARK in f.read():
                        found.append(f"{PAGES}/{name}")
    return found


def differences(root, catalogues):
    problems = []
    want = expected(root, catalogues)
    readme_path = os.path.join(root, README)
    if not os.path.isfile(readme_path):
        problems.append(f"{README} is missing")
    else:
        with open(readme_path, encoding="utf-8") as f:
            if readme(f.read(), catalogues) is None:
                problems.append(f"{README} has no {BEGIN} ... {END} block for the list of components")
    for rel, text in want.items():
        path = os.path.join(root, rel)
        if not os.path.isfile(path):
            problems.append(f"{rel} is missing")
            continue
        with open(path, encoding="utf-8", newline="") as f:
            if f.read() != text:
                problems.append(f"{rel} is not what the catalogues generate")
    for rel in generated_pages(root):
        if rel not in want:
            problems.append(f"{rel} is generated from a catalogue that no longer exists")
    return problems


def write(root, catalogues):
    """Write what differs and delete stale pages; the relative paths changed."""
    changed = []
    for rel, text in expected(root, catalogues).items():
        path = os.path.join(root, rel)
        current = None
        if os.path.isfile(path):
            with open(path, encoding="utf-8", newline="") as f:
                current = f.read()
        if current != text:
            os.makedirs(os.path.dirname(path), exist_ok=True)
            with open(path, "w", encoding="utf-8", newline="") as f:
                f.write(text)
            changed.append(rel)
    want = expected(root, catalogues)
    for rel in generated_pages(root):
        if rel not in want:
            os.remove(os.path.join(root, rel))
            changed.append(rel)
    return changed


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--root", default=".")
    parser.add_argument("--check", action="store_true", help="exit 1 when a generated file is not current")
    parser.add_argument("--index", metavar="FILE", help="also write the A-Z index of every name to FILE")
    args = parser.parse_args(argv)
    root = os.path.abspath(args.root)
    try:
        catalogues = load(root)
    except Refused as refused:
        for problem in refused.args[0]:
            print(problem, file=sys.stderr)
        print(f"{len(refused.args[0])} problem(s) in the catalogues; nothing generated", file=sys.stderr)
        return 1
    if args.index:
        with open(args.index, "w", encoding="utf-8") as f:
            f.write(index(catalogues))
    if args.check:
        problems = differences(root, catalogues)
        for problem in problems:
            print(problem, file=sys.stderr)
        if problems:
            print(f"{len(problems)} generated file(s) not current: run python3 {TOOL} and commit what it writes",
                  file=sys.stderr)
            return 1
        print(f"current: {len(catalogues)} component page(s), {README}'s list and {EXTENDED}")
        return 0
    changed = write(root, catalogues)
    for rel in changed:
        print(f"wrote {rel}")
    print(f"{len(catalogues)} component page(s); {len(changed)} file(s) changed")
    return 0


if __name__ == "__main__":
    sys.exit(main())
