package au.com.idpartners.gm.servlet;

import com.fasterxml.jackson.databind.ObjectMapper;

import javax.servlet.ServletConfig;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import java.io.IOException;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * The Grant Management metadata of section 7.1 — served, with a caveat that matters.
 *
 * <pre>
 *   GET /gm-api/.well-known/grant-management-configuration
 * </pre>
 *
 * <p><b>This is not where the spec puts it.</b> Section 7.1 adds these fields to the
 * authorization server's own metadata, at
 * {@code /.well-known/oauth-authorization-server}, so a client discovers them alongside
 * everything else about the AS. That document is PingFederate's. It is generated by the
 * server, there is no plugin type for extending it, and nothing deployed into
 * {@code server/default/deploy} can add a field to it.
 *
 * <p>So this serves the same fields at a path a servlet can own. A conformant client will
 * not find them here, and should not be expected to: this exists so the values are
 * inspectable and the shape is demonstrable, not to claim discovery works. Making it
 * conformant needs PingFederate to publish the fields itself — see
 * {@code docs/pingfederate-gm-api-gaps.md}.
 *
 * <p>The honesty is the point. Advertising {@code grant_management_endpoint} from a place
 * no client looks would be worse than not advertising it, because it would read as
 * support.
 */
public class MetadataServlet extends HttpServlet {

    private static final ObjectMapper MAPPER = new ObjectMapper();

    private String issuer;
    private String endpoint;

    @Override
    public void init(ServletConfig config) throws ServletException {
        // GenericServlet stores the config here; without it getServletConfig() and
        // getServletContext() silently return null.
        super.init(config);
        this.issuer = config.getInitParameter("issuer");
        this.endpoint = config.getInitParameter("grantManagementEndpoint");
    }

    @Override
    protected void doGet(HttpServletRequest req, HttpServletResponse resp) throws IOException {
        String base = endpoint != null && !endpoint.isBlank()
                ? endpoint
                : baseUrlOf(req) + req.getContextPath() + "/grants";

        Map<String, Object> metadata = new LinkedHashMap<>();
        if (issuer != null && !issuer.isBlank()) {
            metadata.put("issuer", issuer);
        }
        metadata.put("grant_management_endpoint", base);

        // What this deployment can actually do. create/replace/merge are absent because
        // they are section 5 authorization-request actions, which PingFederate ignores
        // and no servlet can implement -- claiming them would be a lie a client could
        // act on.
        metadata.put("grant_management_actions_supported", List.of("query", "revoke", "evaluate"));

        // Section 7.1: whether a client MUST supply grant_management_action. False, and
        // necessarily so: PF ignores the parameter entirely, so requiring it would be
        // unenforceable.
        metadata.put("grant_management_action_required", false);

        // The proposed extension.
        metadata.put("grant_evaluation_supported", true);

        // Not part of any spec. It is here so nobody mistakes this document for the AS's
        // own metadata, which is where section 7.1 actually belongs.
        metadata.put("x_note", "Non-standard location. Section 7.1 places these fields in the "
                + "authorization server's own metadata, which PingFederate generates and does not "
                + "allow a plugin to extend. See docs/pingfederate-gm-api-gaps.md.");

        resp.setStatus(200);
        resp.setContentType("application/json");
        resp.setHeader("Cache-Control", "no-store");
        MAPPER.writeValue(resp.getOutputStream(), metadata);
    }

    /** The URL the client reached us on, honouring a proxy's forwarding headers. */
    private static String baseUrlOf(HttpServletRequest req) {
        String scheme = req.getHeader("X-Forwarded-Proto");
        if (scheme == null || scheme.isBlank()) {
            scheme = req.getScheme();
        }
        String host = req.getHeader("X-Forwarded-Host");
        if (host == null || host.isBlank()) {
            host = req.getServerName() + ":" + req.getServerPort();
        }
        return scheme.split(",")[0] + "://" + host.split(",")[0];
    }
}
